version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Dependencies
        command: |
          git clone --depth 1 -b v1.2.17 https://github.com/pyenv/pyenv.git $HOME/.pyenv
          $HOME/.pyenv/bin/pyenv install 3.5.8
          $HOME/.pyenv/bin/pyenv install 3.7.5
          $HOME/.pyenv/bin/pyenv install 3.8.2
          pip3 install --user tox flake8
          pip3 install --user -r docs/requirements.txt
          make deps
    - run:
        name: make all
        command: |
          make all
    # Test that the documentation is okay
    - run: make test-docs
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results
